"""Phase 4: Community activity feed."""
from fastapi import APIRouter, Depends, HTTPException, Query
from typing import Optional
from datetime import datetime, timezone
from bson import ObjectId

from routes import db, get_current_user, serialize_doc

router = APIRouter(prefix="/api/feed", tags=["feed"])


@router.get("")
async def get_feed(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=50),
    current_user: dict = Depends(get_current_user),
):
    """Get the community activity feed."""
    skip = (page - 1) * limit
    posts = await db.feed_posts.find().sort("createdAt", -1).skip(skip).limit(limit).to_list(limit)

    results = []
    for post in posts:
        doc = serialize_doc(post)
        doc["isLiked"] = current_user["id"] in post.get("likes", [])
        doc["likeCount"] = len(post.get("likes", []))
        results.append(doc)

    total = await db.feed_posts.count_documents({})
    return {"posts": results, "total": total, "page": page, "hasMore": skip + limit < total}


@router.post("/{post_id}/like")
async def toggle_like(post_id: str, current_user: dict = Depends(get_current_user)):
    """Like or unlike a feed post."""
    post = await db.feed_posts.find_one({"_id": ObjectId(post_id)})
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")

    uid = current_user["id"]
    if uid in post.get("likes", []):
        await db.feed_posts.update_one({"_id": ObjectId(post_id)}, {"$pull": {"likes": uid}})
        return {"liked": False, "likeCount": len(post.get("likes", [])) - 1}
    else:
        await db.feed_posts.update_one({"_id": ObjectId(post_id)}, {"$addToSet": {"likes": uid}})
        return {"liked": True, "likeCount": len(post.get("likes", [])) + 1}


async def auto_create_feed_post(
    post_type: str,
    user_id: str,
    user_name: str,
    content: str,
    metadata: dict = None,
):
    """
    Auto-generate feed posts from system events.
    Called internally when sessions complete, badges unlock, streaks hit milestones.
    """
    doc = {
        "postType": post_type,  # session_complete, badge_unlock, streak_milestone, trainer_shoutout, leaderboard
        "userId": user_id,
        "userName": user_name,
        "content": content,
        "metadata": metadata or {},
        "likes": [],
        "createdAt": datetime.now(timezone.utc),
        "isAutoGenerated": True,
    }
    await db.feed_posts.insert_one(doc)


@router.post("")
async def create_feed_post(
    content: str,
    post_type: str = "user_post",
    current_user: dict = Depends(get_current_user),
):
    """User creates a manual feed post (trainer shoutout, etc)."""
    doc = {
        "postType": post_type,
        "userId": current_user["id"],
        "userName": current_user.get("fullName", "User"),
        "content": content,
        "metadata": {},
        "likes": [],
        "createdAt": datetime.now(timezone.utc),
        "isAutoGenerated": False,
    }
    result = await db.feed_posts.insert_one(doc)
    doc["id"] = str(result.inserted_id)
    return serialize_doc(doc)
